import { createSlice } from "@reduxjs/toolkit";

// Initial state of the user slice
const initialState = {
    /* Try adding {username: "john"} into user input rather than null – 
       SPUR profile page will make you sign in because it first verifies 
       to see if the user is an object (they have an account made) */
       
    user: null, // User state starts as null, meaning no user is logged in
    isLoading: true, // Loading state starts as true, indicating a loading process is ongoing
}

// Creating a slice for user management using createSlice
export const userSlice = createSlice({
    name: "user", /* Name of the slice */
    initialState, /* Initial state defined above */
    reducers: {
        /* Reducer to handle user login
           This sets the user state to the payload of the action */
        loginUser: (state, action) => {
            state.user = action.payload;
        },
        /* Reducer to handle user logout
           This sets the user state back to null */
        logoutUser: (state) => {
            state.user = null;
        },
        /* Reducer to set the loading state
           This sets the isLoading state to the payload of the action */
        setLoading: (state, action) => {
            state.isLoading = action.payload;
        }
    }
})

// Exporting the actions generated by createSlice
export const { loginUser, logoutUser, setLoading } = userSlice.actions;
